### PR TITLE
Various documentation additions & make room creation endpoint return a fixed schema result.

### PR DESCRIPTION
**Pull request by EranStockdale**
A preview of my current version of the docs can be found [here](https://hackbox-8ma.pages.dev/).

> make room creation endpoint return a fixed schema result.

basically just ensures the response has either `ok = true` or `ok = false`

### CODE REVIEW

**Review by devanhurst — COMMENTED** [review]
Excellent excellent stuff here. Thanks so much! 🎉 

Before I merge, please remove the yarn.lock files. This project currently uses `npm` for version control.

**Comment by EranStockdale** [comment]
Will do! Sorry, the documentation README mentioned using `yarn` so I did, I'd normally use `npm` anyway haha. I'll get on that now!

**Comment by EranStockdale** [comment]
Done! I will be making more documentation, life just caught up with me a bit.

**Comment by EranStockdale** [comment]
ignore the previous force push - just me being incompetent with git :stuck_out_tongue:

**Review by devanhurst — APPROVED** [review]

**Pull request merged**
